### ISSUE TITLE
Property 'push' does not exist on type 'typeof List' in selectionOps.ts

### ISSUE THREAD

**Issue by lenoch** [czcorpus/kontext#3578]
Build has been failing since 9c1e889bad882237998f76be6e2e129f389792ef:

```js
ERROR in /opt/kontext/public/files/js/models/textTypes/selectionOps.ts
./public/files/js/models/textTypes/selectionOps.ts
[tsl] ERROR in /opt/kontext/public/files/js/models/textTypes/selectionOps.ts(102,22)
      TS2339: Property 'push' does not exist on type 'typeof List'.
```

See the comment on a likely cause: https://github.com/czcorpus/kontext/commit/9c1e889bad882237998f76be6e2e129f389792ef#r44878755

This is why the PR #3577 (please review the TS part!) is based on a previous commit.

**Comment by tomachalek** [comment]
Please note the change in the version of `cnc-tskit` (https://github.com/czcorpus/kontext/commit/9c1e889bad882237998f76be6e2e129f389792ef#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R38)
`npm update` or `npm install` should do the job.

**Comment by lenoch** [comment]
Thanks, that helped! (Though I had to google a `npm install --save-dev "webpack@^5.1.0"`, to resolve peer dependencies.)

...

What do you think of #3577? I have rebased it on top of `master` (after testing the build and the fix).
